ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.andrii.SerializationKt.configureSerialization
      - com.andrii.RoutingKt.configureAuthentication
      - com.andrii.RoutingKt.configureRouting
